[package]
name = "rai-pal-tauri"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
log.workspace = true
rai-pal-core.workspace = true
rai-pal-proc-macros.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
serde.workspace = true
specta.workspace = true
strum.workspace = true
tauri-specta.workspace = true
thiserror.workspace = true

rfd = { version = "0.17.2", default-features = false, features = ["gtk3"] }
specta-typescript = "0.0.12"
tokio = "1.52.3"
tauri = { version = "2.11.5", features = ["protocol-asset", "config-toml"] }
tauri-plugin-dialog = "2.7.1"
tauri-plugin-log = "2.8.0"
tauri-plugin-os = "2.3.2"
tauri-plugin-updater = "2.10.1"
tauri-plugin-window-state = "2.4.1"
tauri-runtime = "2.11.3"
tauri-plugin-deep-link = "2.4.9"
tauri-plugin-single-instance = { version = "2.4.2", features = ["deep-link"] }

[features]
# This feature is used for production builds or when `devPath` points to the filesystem.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
# This will be the installed exe name (not the installer name).
name = "Rai-Pal"
# This would usually already be the default path,
# but when a custom name is defined it gets inferred from the name.
# So we need to specify it here to override the inferred one.
path = "src/main.rs"

[lints]
workspace = true
