name: publish-builder-images

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Containerfile.linux
      - Containerfile.windows
      - .github/workflows/publish-builder-images.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-name: linux
            containerfile: Containerfile.linux
          - os-name: windows
            containerfile: Containerfile.windows

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/raicuparta/rai-pal-builder
          tags: |
            type=raw,value=${{ matrix.os-name }}-latest
            type=sha,format=short,prefix=${{ matrix.os-name }}-

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.containerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
