name: "release"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release-matrix:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            os-name: windows
          - platform: ubuntu-24.04
            os-name: linux

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: "npm"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-24.04'
        # bug: https://github.com/audioling/audioling/issues/40
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-0=2.44.0-2 \
            libwebkit2gtk-4.1-dev=2.44.0-2 \
            libjavascriptcoregtk-4.1-0=2.44.0-2 \
            libjavascriptcoregtk-4.1-dev=2.44.0-2 \
            gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
            gir1.2-webkit2-4.1=2.44.0-2 \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm ci

      - name: Prepare Release Metadata
        id: pre
        run: node scripts/pre-release.js

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          ANALYTICS_API_KEY: ${{ secrets.ANALYTICS_API_KEY }}
        with:
          tagName: v${{ steps.pre.outputs.version }}
          releaseName: v${{ steps.pre.outputs.version }}
          releaseBody: ${{ steps.pre.outputs.body_path }}
          releaseDraft: true
          prerelease: false
          releaseAssetNamePattern: "RaiPal"
          uploadUpdaterJson: false
          uploadUpdaterSignatures: true

      - name: Generate Custom Updater JSON
        run: node scripts/generate-updater-json.js ${{ steps.pre.outputs.version }} ${{ github.repository_owner }} ${{ github.event.repository.name }}

      - name: Upload Updater JSON
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.pre.outputs.version }}
          files: latest-${{ matrix.os-name }}.json
          draft: true
